# action.yml
name: "Hello World"
description: "Greet someone and record the time"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - "pwd"
      # - "changelog-checker"
      # - "/github/workspace"
