# action.yml
name: "Hello World"
description: "Greet someone and record the time"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - "ls"
    - "-la"
      # - "changelog-checker"
      # - "/github/workspace"
