[package]
name = "changelog-checker"
version = "1.0.1"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
colored = "2.0.4"
lexopt = "0.3.0"
reqwest = { version = "0.11.22", features = ["json", "blocking", "rustls-tls"], default-features = false }
serde = { version = "1.0.189", features = ["derive"] }
